baseURL = 'https://aideception.org/'
languageCode = 'en-us'
title = 'AI Deception Papers'
theme = 'simple'

[params]
  description = 'A curated database of research papers on AI deception with philosophical and cognitive science commentary'
  author = 'Chris Rathkopf'
  site_logo = ''
  text_color = 'dark-gray'
  background_color_class = 'bg-near-white'
  recent_posts_number = 10

[[menu.main]]
  name = "Papers"
  url = "/papers/"
  weight = 10

[[menu.main]]
  name = "Deception Types"
  url = "/deception_types/"
  weight = 20

[[menu.main]]
  name = "Research Areas"
  url = "/research_areas/"
  weight = 30

[[menu.main]]
  name = "System Types"
  url = "/system_types/"
  weight = 40

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 50

[taxonomies]
  deception_type = 'deception_types'
  research_area = 'research_areas'
  system_type = 'system_types'
  tag = 'tags'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
