baseURL = 'https://aideception.org/'
languageCode = 'en-us'
title = 'AI Deception Papers'
theme = 'simple'

[params]
  description = 'Research papers on AI deception with philosophical analysis by Charles Rathkopf'
  author = 'Charles Rathkopf'
  site_logo = ''
  text_color = 'dark-gray'
  background_color_class = 'bg-near-white'
  recent_posts_number = 10

[params.analytics.google]
  SiteVerificationTag = "G-QRVCJ9K4DJ"

[[menu.main]]
  name = "Papers"
  url = "/papers/"
  weight = 10

[[menu.main]]
  name = "Glossary"
  url = "/glossary/"
  weight = 20

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 30

[taxonomies]
  deception_type = 'deception_types'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
